### ISSUE TITLE
Xamarin.Forms support?

### ISSUE THREAD

**Issue by sarseniev** [CodonFramework/Samples#1]
Does Codon supports Xamarin.Forms? I am getting "Unable to resolve mapping for type 'Codon.Services.IDialogService' There is a default type 'Codon.DialogModel.DialogService, Codon.Platform' that was expected to be found in a platform specific library." error message in Xamarin.Forms shared project. Following nugets added to the Xamarin.Forms iOS projects:
- Codon
- Codon.Essentials
- Codon.Extras
- Codon.Extras.Core
- Codon.Extras.Ios
- Codon.Ios
- Xamarin.Forms

**Comment by DVaughan** [comment]
Yes, but I've not implemented IDialogService specifically for Xamarin Forms. However you can register each of the platform specific implementations in your Android or iOS app projects like so: Dependency.Register<IDialogService, DialogService>(). 
Android, iOS, UWP and WPF each have an IDialogService implementation.

**Comment by sarseniev** [comment]
Works as expected. Thank you, Daniel.
