### ISSUE TITLE
Bootstrapper code - target specific ?

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Samples#9]
Does the bootstrapper code (needed for instance for the NavigationService) has to be target platform-dependent ? Would be possible to move it to a NetStandard 2 class library?

**Comment by DVaughan** [comment]
Keep in mind, you might find there are platform specific things that need initializing.

**Comment by abrasat** [comment]
Thx, you are right.
My question was if the Codon NavigationService is target-specific.
